<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "agora"
 *
 * Auto generated by Extension Builder 2015-02-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Agora - TYPO3 Forum',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Phillip Thiele, Björn Christopher Bresser',
	'author_email' => 'philipp.thiele@phth.de, bjoern.bresser@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);